name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint
    runs-on: self-hosted
    container: circleci/android:api-28-node
    steps:
      - uses: actions/checkout@v2
      - name: Adding credential
        shell: bash
        run: |
          echo "$KEYSTORE" > app/keystore-decoded.txt
          base64 -d app/keystore-decoded.txt > app/keystore-tktpl-proj.jks
          echo "$KEYSTORE_PROPERTIES" > keystore.properties
          echo "$GOOGLE_SERVICE" > app/google-services.json
          chmod +x gradlew
        env:
          KEYSTORE: ${{secrets.KEYSTORE}}
          KEYSTORE_PROPERTIES: ${{secrets.KEYSTORE_PROPERTIES}}
          GOOGLE_SERVICE: ${{secrets.GOOGLE_SERVICE}}
      - name: Lint code
        run: |
          ./gradlew lint
