name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Adding credential
        shell: bash
        run: |
          echo "$KEYSTORE" > app/keystore-decoded.txt
          base64 -d app/keystore-decoded.txt > app/keystore-tktpl-proj.jks
          echo "$KEYSTORE_PROPERTIES" > keystore.properties
          echo "$GOOGLE_SERVICE" > app/google-services.json
          chmod +x gradlew
        env:
          KEYSTORE: ${{secrets.KEYSTORE}}
          KEYSTORE_PROPERTIES: ${{secrets.KEYSTORE_PROPERTIES}}
          GOOGLE_SERVICE: ${{secrets.GOOGLE_SERVICE}}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive apk generated
        uses: actions/upload-artifact@v2
        with:
          name: apk-generated
          path: app/build/outputs/apk/release
